/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ComparisonResult = IDL.Record({
  'status' : IDL.Text,
  'differences' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'profileType' : IDL.Text,
});
export const Doctor = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'languages' : IDL.Vec(IDL.Text),
  'experience' : IDL.Nat,
  'specialty' : IDL.Text,
  'availability' : IDL.Vec(IDL.Nat),
  'certifications' : IDL.Vec(IDL.Text),
  'consultationFee' : IDL.Nat,
  'location' : IDL.Text,
});
export const HireRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'doctorPrincipal' : IDL.Principal,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
  'hospitalPrincipal' : IDL.Principal,
});
export const Hospital = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'size' : IDL.Text,
  'specialization' : IDL.Text,
  'location' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'principal' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const AggregatedData = IDL.Record({
  'topSpecialties' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'compareAggregatedData' : IDL.Func(
      [],
      [IDL.Vec(ComparisonResult)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDoctor' : IDL.Func([IDL.Principal], [Doctor], ['query']),
  'getHireRequests' : IDL.Func([], [IDL.Vec(HireRequest)], ['query']),
  'getHospital' : IDL.Func([IDL.Principal], [Hospital], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listAggregatedData' : IDL.Func([], [IDL.Vec(AggregatedData)], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'listHospitals' : IDL.Func([], [IDL.Vec(Hospital)], ['query']),
  'registerDoctor' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Nat),
        IDL.Nat,
      ],
      [],
      [],
    ),
  'registerHospital' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'requestApproval' : IDL.Func([], [], []),
  'respondToHireRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendHireRequest' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ComparisonResult = IDL.Record({
    'status' : IDL.Text,
    'differences' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'profileType' : IDL.Text,
  });
  const Doctor = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'languages' : IDL.Vec(IDL.Text),
    'experience' : IDL.Nat,
    'specialty' : IDL.Text,
    'availability' : IDL.Vec(IDL.Nat),
    'certifications' : IDL.Vec(IDL.Text),
    'consultationFee' : IDL.Nat,
    'location' : IDL.Text,
  });
  const HireRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'doctorPrincipal' : IDL.Principal,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
    'hospitalPrincipal' : IDL.Principal,
  });
  const Hospital = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'size' : IDL.Text,
    'specialization' : IDL.Text,
    'location' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'principal' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const AggregatedData = IDL.Record({
    'topSpecialties' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'compareAggregatedData' : IDL.Func(
        [],
        [IDL.Vec(ComparisonResult)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDoctor' : IDL.Func([IDL.Principal], [Doctor], ['query']),
    'getHireRequests' : IDL.Func([], [IDL.Vec(HireRequest)], ['query']),
    'getHospital' : IDL.Func([IDL.Principal], [Hospital], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listAggregatedData' : IDL.Func([], [IDL.Vec(AggregatedData)], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'listHospitals' : IDL.Func([], [IDL.Vec(Hospital)], ['query']),
    'registerDoctor' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Nat),
          IDL.Nat,
        ],
        [],
        [],
      ),
    'registerHospital' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'requestApproval' : IDL.Func([], [], []),
    'respondToHireRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendHireRequest' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };