/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AggregatedData { 'topSpecialties' : Array<[string, bigint]> }
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ComparisonResult {
  'status' : string,
  'differences' : Array<string>,
}
export interface Doctor {
  'principal' : Principal,
  'name' : string,
  'languages' : Array<string>,
  'experience' : bigint,
  'specialty' : string,
  'availability' : Array<bigint>,
  'certifications' : Array<string>,
  'consultationFee' : bigint,
  'location' : string,
}
export interface HireRequest {
  'id' : bigint,
  'status' : string,
  'doctorPrincipal' : Principal,
  'timestamp' : bigint,
  'details' : string,
  'hospitalPrincipal' : Principal,
}
export interface Hospital {
  'principal' : Principal,
  'name' : string,
  'size' : string,
  'specialization' : string,
  'location' : string,
}
export interface Notification {
  'id' : bigint,
  'principal' : Principal,
  'message' : string,
  'timestamp' : bigint,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string, 'profileType' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'compareAggregatedData' : ActorMethod<[], Array<ComparisonResult>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDoctor' : ActorMethod<[Principal], Doctor>,
  'getHireRequests' : ActorMethod<[], Array<HireRequest>>,
  'getHospital' : ActorMethod<[Principal], Hospital>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listAggregatedData' : ActorMethod<[], Array<AggregatedData>>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listDoctors' : ActorMethod<[], Array<Doctor>>,
  'listHospitals' : ActorMethod<[], Array<Hospital>>,
  'registerDoctor' : ActorMethod<
    [
      string,
      string,
      bigint,
      string,
      Array<string>,
      Array<string>,
      Array<bigint>,
      bigint,
    ],
    undefined
  >,
  'registerHospital' : ActorMethod<[string, string, string, string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'respondToHireRequest' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendHireRequest' : ActorMethod<[Principal, string], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];